before_commands:
    - "composer install --no-dev --prefer-source"

tools:
    external_code_coverage:
        timeout: 3600
    php_code_coverage:
        enabled: true
    php_code_sniffer:
        enabled: true
    php_cpd:
        enabled: true
        excluded_dirs: ["src", "spec", "vendor", "bin"]
    php_cs_fixer:
        enabled: true
    php_loc:
        enabled: true
        excluded_dirs: ["src", "spec", "vendor", "bin"]
    php_mess_detector:
        enabled: true
        filter:
            paths: ["src/*"]
    php_pdepend:
        enabled: true
        excluded_dirs: ["spec", "vendor", "bin"]
    php_analyzer:
        enabled: true
        filter:
            paths: ["src/*", "spec/*"]
    sensiolabs_security_checker: true
checks:
    php:
        code_rating: true
        duplication: true
build:
    tests:
        override:
            -
                command: 'bin/phpspec run -f progress -c phpcpec.yml.dist'
                coverage:
                    file: 'coverage/coverage.clover'
                    format: 'php-clover'